---
title: "Mobile Phones"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)
library(plotly)

library(data.table)
assignInNamespace("cedta.override", c(data.table:::cedta.override,"rmarkdown"), "data.table")


opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)

```

```{r source_functions}
source("constants.R")
source("functions.R")
```



```{r read_data}
dat <- fread(input = "../Data/mobile phone survey data.csv", verbose = F)
```

```{r clean_data}
  dat[, `Age Group` :=
  fcase(
  Age < 35 & Age >= 18 , '18-34',
	Age < 50, '35-49',
	Age< 65, '50-64',
	Age >= 65, '65+'
)]
dat[, `Income Group`:=
  fcase(
    Income<50000,'[     0, 50000)',
    Income<75000,'[ 50000, 75000)',
    Income<100000,'[ 75000,100000)',
    Income<150000,'[100000,150000)',
    Income>=150000,'[150000,197000]'
  )]

```


```{r define_variables}
dat[, eval(satisfaction.name) := get(satisfaction.name) / value.max.satisfaction]
unique.age.groups <- dat[, sort(unique(get(age.group.name)))]
unique.genders <- dat[, sort(unique(get(gender.name)))]
unique.income.groups <- dat[, sort(unique(get(income.group.name)))]
unique.regions <- dat[, sort(unique(get(region.name)))]
unique.personas <- dat[, sort(unique(get(persona.name)))]
unique.products <- dat[, unique(get(product.name))]

respondent.variables <- c(age.group.name, gender.name, income.group.name, region.name, persona.name)
states.of.engagement <- c(awareness.name, consideration.name, consumption.name, satisfaction.name, advocacy.name)
bp.traits <- names(dat)[grep(pattern = bp.pattern, x = names(dat))]
dat.clean<- na.omit(dat,cols=bp.traits)
cols<-c("BP_Boring_0_10","BP_Bulky_0_10","BP_Fragile_0_10","BP_Expensive_0_10")
dat.clean[,(cols) :=  lapply(.SD, function(x) 10-x), .SDcols=cols]
```

Introduction
=====================================  

```{r}
unique.cus<-dat[,length(unique(get(id.name)))]
unique.prod<-dat[,length(unique(get(product.name)))]
```


There are `r unique.cus` respondents took the survey and it covered `r unique.prod` products.

click on the tabs to see different reports.


Question 1
===================================


Inputs {.sidebar}
-------------------------------------

```{r q1_input}
inputPanel(
  selectInput(inputId="respondent_variable", label = "Select Variable:", choices = respondent.variables, selected = respondent.variables[1]),
  checkboxInput(inputId = "respondent_show_percentages", label = "Show Percentages", value = TRUE)
)
```

Row {data-height=500}
-------------------------------------

```{r q1_output}
renderPlot({
  tab <- percentage.table(x = dat[, .SD[1], by = "id"][, get(input$respondent_variable)])
  barplot(height = tab, space=0.01, las = 1, main = input$respondent_variable, ylab = "Percentage", xlab = input$respondent_variable, ylim = c(0, 1.2*max(tab, na.rm = TRUE)), col = "dodgerblue")
  
  if(input$respondent_show_percentages == TRUE){
    space_val = 0
    text(x = -0.4 + 1:length(tab) * (1+space_val), y = tab, labels = sprintf("%.1f%%", tab), pos = 3)
  }
})
```

Question 2
=====================================  


Inputs {.sidebar}
-------------------------------------

```{r q2_input}
inputPanel(
   sliderInput(inputId = "product_rank", label = "Show Product Ranking Top", min = 0, max = 20, value = 5, step = 1),
  selectInput(inputId="em_state", label = "State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="em_age_group", label = "Age", choices = unique.age.groups, selected = unique.age.groups, multiple = TRUE),
  selectInput(inputId = "em_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = TRUE),
  selectInput(inputId = "em_income_group", label = "Income", choices = unique.income.groups, selected = unique.income.groups, multiple = TRUE),
  selectInput(inputId = "em_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = TRUE),
  selectInput(inputId = "em_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = TRUE)
 
)
```

Row {data-height=500}
-------------------------------------

```{r q2_output}
renderPlot({
  rates <- dat[ get(age.group.name) %in% input$em_age_group & get(gender.name) %in% input$em_gender & get(income.group.name) %in% input$em_income_group & get(region.name) %in% input$em_region & get(persona.name) %in% input$em_persona, .(Mean = 100*mean(get(input$em_state), na.rm=TRUE)), by = product.name]
   show_Segmented_Outcomes(rates,input$em_state,input$product_rank)

})

 
```




Question 3
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r q3_input}
inputPanel(
  sliderInput(inputId = "q3_rank", label = "Show Product Ranking Top", min = 1, max = 20, value = 5, step = 1),
  selectInput(inputId="q3_age_group", label = "Age", choices = unique.age.groups, selected = unique.age.groups, multiple = TRUE),
  selectInput(inputId = "q3_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = TRUE),
  selectInput(inputId = "q3_income_group", label = "Income", choices = unique.income.groups, selected = unique.income.groups, multiple = TRUE),
  selectInput(inputId = "q3_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = TRUE),
  selectInput(inputId = "q3_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = TRUE)

)
```

Row {data-height=500}
-------------------------------------
```{r q3_output}
renderPlot({
  bp.mean <- dat.clean[get(age.group.name) %in% input$q3_age_group & get(gender.name) %in% input$q3_gender & get(income.group.name) %in% input$q3_income_group& get(region.name) %in% input$q3_region & get(persona.name) %in% input$q3_persona,]
  
q3_show_bp(bp.mean,input$q3_rank,bp.traits) 
})
```



Question 4
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r q4_input}
inputPanel(
  selectInput(inputId="outcome1", label = "Select State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="outcome2", label = "Select State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[2]),
  sliderInput(inputId = "q4_rank", label = "Show Product Ranking Top", min = 1, max = 20, value = 5, step = 1),
  checkboxInput(inputId = "ep_show_percentages", label = "Show Percentages", value = TRUE)
)

```

Row {data-height=1000}
-------------------------------------

```{r q4_output}
renderPlot({
  gap<-dat[, .(Mean = 100*mean(get(input$outcome1), na.rm=TRUE)-100*mean(get(input$outcome2), na.rm=TRUE)),by=product.name]
setorderv(x = gap, cols = "Mean", order = -1)
    barplot(height = gap[1:input$q4_rank, Mean], space=0.01, las = 1, main = sprintf("Gap in Outcomes: %s - %s", input$outcome1,input$outcome2),ylab="Percentage", ylim = c(1.2 * min(gap[, Mean], na.rm = TRUE), 1.2 * max(gap[, Mean], na.rm = TRUE)), col = "dodgerblue")

    
   for(i in 1:input$q4_rank){
     if(gap[i, Mean]>0){
       text(x =-0.5 +1.02*i, y=-1,labels = gap[i, get(product.name)], srt = 45, pos = 2)
     }else{
        text(x =1.02*i, y=22,labels = gap[i, get(product.name)], srt = 45,pos = 3)
     }
   }

    if(input$ep_show_percentages == TRUE){
      space_val = 0
      for(i in 1:input$q4_rank){
        
         if(gap[i, Mean]>0){
           text(x = -0.4 + i * (1+space_val), y = gap[i, Mean], labels = sprintf("%.1f%%", gap[i, Mean]), pos = 3)
         }else{
            text(x = -1 + i * (1+space_val), y = gap[i, Mean]-10, labels = sprintf("%.1f%%", gap[i, Mean]), pos = 4)
         }
       }

    }
})
```

Question 5
=====================================  

Row {data-height=500}
-------------------------------------


```{r q5_input}
inputPanel(
  selectInput(inputId="q5_state", label = "State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  selectInput(inputId="q5_product", label = "Brand", choices = unique.products, selected = unique.products[1], multiple = TRUE),
  selectInput(inputId="q5_inputs", label = "Choose Inputs:", choices = c(age.group.name, gender.name, region.name, income.group.name, persona.name, bp.traits,aggregated.name), selected = c(age.group.name, gender.name, region.name, income.group.name,aggregated.name), multiple = TRUE),
  selectInput(inputId="q5_age_group", label = "Age", choices = unique.age.groups, selected = unique.age.groups, multiple = TRUE),
  selectInput(inputId = "q5_gender", label = "Gender", choices = unique.genders, selected = unique.genders, multiple = TRUE),
  selectInput(inputId = "q5_income_group", label = "Income", choices = unique.income.groups, selected = unique.income.groups, multiple = TRUE),
  selectInput(inputId = "q5_region", label = "Region", choices = unique.regions, selected = unique.regions, multiple = TRUE),
  selectInput(inputId = "q5_persona", label = "Persona", choices = unique.personas, selected = unique.personas, multiple = TRUE)
)
```

Row {data-height=1000}
-------------------------------------

```{r q5_output,height=600}
renderDataTable({
  if(input$q5_state == satisfaction.name){
    
    model.type <- "linear"
 }
  if(input$q5_state != satisfaction.name){
    
    model.type <- "logistic"
  }
  q5_model(dat,input$q5_state,input$q5_product,input$q5_age_group,input$q5_gender,input$q5_income_group,input$q5_region,input$q5_persona,model.type)

})


```

